### ISSUE TITLE
When delivery-cluster uses artifactory it fails

### ISSUE THREAD

**Issue by afiune** [opscode-cookbooks/delivery-cluster#103]
Trying to use artifactory to install delivery we got now this:

````
    ================================================================================
    Error executing action `converge` on resource 'machine[delivery-server-aws]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `uri' for nil:NilClass

    Cookbook Trace:
    ---------------
    /Users/salimafiune/github/delivery-cluster/.chef/local-mode-cache/cache/cookbooks/delivery-cluster/libraries/artifactory_helper.rb:90:in `get_delivery_artifact'
    /Users/salimafiune/github/delivery-cluster/.chef/local-mode-cache/cache/cookbooks/delivery-cluster/libraries/_helper.rb:352:in `delivery_artifact'
    /Users/salimafiune/github/delivery-cluster/.chef/local-mode-cache/cache/cookbooks/delivery-cluster/libraries/_helper.rb:303:in `delivery_server_attributes'
    /Users/salimafiune/github/delivery-cluster/.chef/local-mode-cache/cache/cookbooks/delivery-cluster/recipes/setup_delivery.rb:110:in `block (2 levels) in from_file'

    Resource Declaration:
    ---------------------
    # In /Users/salimafiune/github/delivery-cluster/.chef/local-mode-cache/cache/cookbooks/delivery-cluster/recipes/setup_delivery.rb

    102: machine delivery_server_hostname do
    103:   chef_server lazy { chef_server_config }
    104:   recipe 'delivery-cluster::delivery'
    105:   files(
    106:     '/etc/delivery/delivery.pem' => "#{cluster_data_dir}/delivery.pem",
    107:     '/etc/delivery/builder_key' => "#{cluster_data_dir}/builder_key",
    108:     '/etc/delivery/builder_key.pub' => "#{cluster_data_dir}/builder_key.pub"
    109:   )
    110:   attributes lazy { delivery_server_attributes }
    111:   converge true
    112:   action :converge
    113: end
    114:

````

Debugging I have discovered that the version has weird characters:
````
[14] pry(#<Chef::Resource::Machine>)> deliv_version="0.3.41+"
=> "0.3.41+"
````

**Comment by alexmanly** [comment]
Is this because of the way the version string is being split on this line:

https://github.com/opscode-cookbooks/delivery-cluster/blob/master/libraries/artifactory_helper.rb#L91

**Comment by afiune** [comment]
@alexmanly nope, it is because the way the artifactory search works.... 

```
[2] pry(#<Chef::Resource::Machine>)> client.artifact_latest_version(
[2] pry(#<Chef::Resource::Machine>)*   repos: artifactory_omnibus_repo,
[2] pry(#<Chef::Resource::Machine>)*   group: 'com.getchef',
[2] pry(#<Chef::Resource::Machine>)*   name: 'delivery',
[2] pry(#<Chef::Resource::Machine>)*   version: version == 'latest' ? '*' : version
[2] pry(#<Chef::Resource::Machine>)* )
=> "0.3.41+"
```

**Comment by afiune** [comment]
Fixed with https://github.com/opscode-cookbooks/delivery-cluster/pull/104
